### ISSUE TITLE
File Sort Flags not bound

### ISSUE THREAD

**Issue by briandinsmore** [na--/ebook-tools#1] opened 2017-11-14 16:29 UTC
`./organize-ebooks.sh: line 311: FILE_SORT_FLAGS[@]: unbound variable`

File sort flags is not a bound variable upon cloning the repo.

Ubuntu 16.04.3 LTS

**Comment by asc6** [comment] 2017-11-14 16:49
I’m seeing this too on Ubuntu 16.04 server

**Comment by zeryl** [comment] 2017-11-14 18:02
Also seeing this on 16.04 (Linux on Windows 10, Ubuntu)

**Comment by na--** [comment] 2017-11-14 20:14
I think [this](https://stackoverflow.com/questions/7577052/bash-empty-array-expansion-with-set-u) is the reason... ah, the joys of bash :)
The issue does not appear in archlinux or debian sid (bash 4.4.12), however Ubuntu 16.04 uses bash 4.3.48 and I was able to reproduce it in a docker container. I'll push a fix in a bit, there are a lot of places that use potentially empty arrays in the code...

**Comment by na--** [comment] 2017-11-14 21:21
This should fix the issue and similar ones. Please test the new code and report if everything is OK so I can close the issue.

btw I tested the changes in a Ubuntu 16.04 docker container and the specific issue was fixed, but calibre appears to be a bit too old - version 2.55. If that's the case with you, please consider using a newer calibre version, the scripts require versions newer than 2.84. If you don't want to upgrade, you can work around the issue by using `--metadata-fetch-order=""` as an argument, though you can expect worse and more inconsistent results when fetching metadata by ISBN.

**Closed** 2017-11-14 21:30 UTC
